site_name: Why For You
theme:
  name: material
  palette:
    - scheme: default       # Light theme
      primary: green
      accent: indigo
      toggle:
        icon: material/weather-night  # Dark mode icon
        name: Switch to dark mode
    - scheme: slate         # Dark theme
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode

# extra_css:
#       - extra.css

# extra_javascript:
#        - extra.js

#   palette:
#     scheme: default
#     primary: green
#     accent: indigo


  features:
    - navigation.tabs
    #- navigation.expand
    #- navigation.sections
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight

#
# Mk_doc\docs\Aws\3.Storage\1.S3\1.S3_General_Buckets.md

nav:
  - Home: index.md
  - AWS:
      - Networking:
          - Virtual_pravite_Network: 
             - Notes : Aws/1.Networking/1.Vpc/1.vpc.md
             - Hands_On: Aws/1.Networking/1.Vpc/2.Hands_On.md
             - Interview_Q&A: Aws/1.Networking/1.Vpc/3.Interview_Q&A.md
          - Route53:
             - Notes: Aws/1.Networking/2.Route53/1.Route53.md
             - Hands_On: Aws/1.Networking/2.Route53/2.Hands_On.md
             - Interview_Q&A: Aws/1.Networking/2.Route53/3.Interview_Q&A.md
          - Cloud Front:
             - Notes: Aws/1.Networking/3.CloudFront/1.CloudFront.md
             - Hands_On: Aws/1.Networking/3.CloudFront/2.Hands_On.md
             - Interview_Q&A: Aws/1.Networking/3.CloudFront/3.Interview_Q&A.md
          - Direct_Connect:
             - Notes: Aws/1.Networking/4.Direct_Connect/1.Direct_Connect.md
             - Hands_On: Aws/1.Networking/4.Direct_Connect/2.Hands_On.md
             - Interview_Q&A: Aws/1.Networking/4.Direct_Connect/3.Interview_Q&A.md

      - Compute:
          - 1.Vpc: Aws/1.NetworkingCloudFront\1.CloudFront.md
      - Storage:
          - S3:
             - Notes: Aws\3.Storage\1.S3\1.S3_General_Buckets.md
             - Features: Aws/3.Storage/1.S3/2.S3_Features.md
             - Hands_on: Aws/3.Storage/1.S3/3.S3_Hands_On_1.md
             - Hands_on_Adv: Aws/3.Storage/1.S3/4.S3.Hands_On_2.md
             - Interview_Q&A: Aws/3.Storage/1.S3/5.Interview_Quetions.md
          
          - Ebs:
             - Notes: Aws/3.Storage/2.Ebs/1.Ebs.md
             - Hands_On: Aws\3.Storage\2.Ebs\2.Hands_On.md
             - Interview_Q&A: Aws\3.Storage\2.Ebs\3.Interview_Q&A.md
          - Efs:
             - Notes: Aws/3.Storage/3.Efs/1.Efs.md
             - Hands_On: Aws\3.Storage\3.Efs\2.Hands_On.md
             - Interview_Q&A: Aws\3.Storage\3.Efs\3.Interview_Q&A.md
          - Efx:
             - Notes: Aws/3.Storage/4.Efx/1.Efx.md
             - Hands_On: Aws\3.Storage\4.Efx\2.Hands_On.md
             - Interview_Q&A: Aws\3.Storage\4.Efx\3.Interview_Q&A.md
          - Storage_gate_way:
             - Notes: Aws\3.Storage\5.Storage_gate_way\5.Storate_gate_way.md

 

# Mk_doc\docs\Master_EKS\Docker\Notes.md

  - Interview:
      
      - challenges: interview.md
      - devops Q&A: interview2.md
      - my_project: interview3.md
  - Eks:
      - Docker: Master_EKS/Docker/Notes.md
      - Eks Introduction:
          - 1.kubernetes Container Intro: Master_EKS/Part1.Eks_intro/1.K8s_Container_Intro.md
          - 2.Eks Introduction: Master_EKS/Part1.Eks_intro/2.Eks_introduction.md
          - 3.Building Eks Cluster: Master_EKS/Part1.Eks_intro/3.Building_Eks_Cluster.md
          - 4.Building your app: Master_EKS/Part1.Eks_intro/4.Building_your_app.md
          - 5.Helm charts Manage app: Master_EKS/Part1.Eks_intro/5.Helm_charts_Manage_app.md
      - Eks Deep Dive:
          - 6.Securing-Accessing: Master_EKS/Part2.Eks_Deep_dive/6.Securing-Accessing.md
          - 7.Networking: Master_EKS/Part2.Eks_Deep_dive/7.Networking.md
          - 8.Worker Nodes: Master_EKS/Part2.Eks_Deep_dive/8.Worker_Nodes.md
          - 9.Advanced Networking: Master_EKS/Part2.Eks_Deep_dive/9.Advanced_Networking.md
          - 10.Upgrading Eks: Master_EKS/Part2.Eks_Deep_dive/10.Upgrading_Eks.md
      - Deploy Application:
          - 11.Build Push ECR: Master_EKS/Part3.Deploying_application/11.Build_Push_ECR.md
          - 12.Deploy_with_aws_storage: Master_EKS/Part3.Deploying_application/12.Deploying_with_AWS_Storage.md
          - 13.IAM_Granting_access_App: Master_EKS/Part3.Deploying_application/13.IAM_Granting_Access_App.md
          - 14.Load_Balancing: Master_EKS/Part3.Deploying_application/14.Load_Balancing_with_Eks.md
          - 15.Work_with_Fargate: Master_EKS/Part3.Deploying_application/15.Working_with_AWS_Fargate.md
          - 16.working_with_Service_Mesh: Master_EKS/Part3.Deploying_application/16.working_with_Service_Mesh.md
      - Eks_Mesh_Service: 
          - 17.Eks_Observbility: Master_EKS/Part4.Advanced_Eks_Mesh_Servcie/17.Eks_Observability.md
          - 18.Scaling_Eks_Cluster: Master_EKS/Part4.Advanced_Eks_Mesh_Servcie/18.Scaling_Eks_Cluster.md
          - 19.Deploying_On_Eks: Master_EKS/Part4.Advanced_Eks_Mesh_Servcie/19.Deploying_On_Eks.md
      - Common_Challenges:
          - 20.Troubleshoot: Master_EKS/part5.Overcomming_common_challenges\20.TroubleShooting.md

#  Mk_doc\docs\Master_EKS\Part4.Advanced_Eks_Mesh_Servcie\19.Deploying_On_Eks.md

     
      - Interview: 
          - 1.kubernetes: Master_EKS/Interview/1.Kubernetes.md
      - Open_telemetry_practise: Master_EKS/Real_world_practise/simple_eks_with_argo.md
#  Mk_doc\docs\Master_EKS\Real_world_practise\simple_eks_with_argo.md

# Mk_doc\docs\sql.md
  - Sql: 
    - sql: sql.md
    - sql_confusing: sql_confusing.md
    - sql_interview: sql_interview.md

#M Mk_doc\docs\Python\Interview\Concept_wise\3.Module_packages.md

  - Python:
      - Interview: 
          - Data_Types: Python/Interview/Concept_wise/1.Objects.md
          - Function_Generators : Python/Interview/Concept_wise/2.Functions_generators.md
          - Module_Packages: Python/Interview/Concept_wise/3.Module_packages.md
          - copy : Python/Interview/Concept_wise/copy.md
      - Part1:Getting Started : 
          - 1.Python_Q&A: Python/Part1.Getting_Started/1.Python_Q&A.md
          - 2.How_Python_Run_Programs: Python/Part1.Getting_Started/2.How_Python_Run_Programs.md
          - 3.How_You_Run_Programs: Python/Part1.Getting_Started/3.How_You_Run_Programs.md
      - Part2.Objects Operations : 
          - 4.Introducing_Python_Objects: Python/Part2.Objects_Operations/4.Introducing_Python_Objects.md
          - 5.Numbers_&_Expressions: Python/Part2.Objects_Operations/5.Numbers_&_Expressions.md
          - 6.Python_Dynamic_Typing_Interlude: Python/Part2.Objects_Operations/6.Python_Dynamic_Typing_Interlude.md
          - 7.String_Fundamentals: Python/Part2.Objects_Operations/7.String_Fundamentals.md
          - 8.List_&_Directionaries: Python/Part2.Objects_Operations/8.List_&_Directionaries.md
          - 9.Tuples_Files_Everything_Else: Python/Part2.Objects_Operations/9.Tuples_Files_Everything_Else.md
      - Part3.Statements Syntax : 
          - 10.Python_Statements: Python/Part3.Statements_Syntax/10.Python_Statements.md
          - 11.Assignments_Expressions_Prints: Python/Part3.Statements_Syntax/11.Assignments_Expressions_Prints.md
          - 12.If_Match_Selections: Python/Part3.Statements_Syntax/12.If_Match_Selections.md
          - 13.While_for_Loops: Python/Part3.Statements_Syntax/13.While_for_Loops.md
          - 14.Iterations_Comprehensions: Python/Part3.Statements_Syntax/14.Iterations_Comprehensions.md
          - 15.Documentation_Interlude: Python/Part3.Statements_Syntax/15.Documentation_Interlude.md

      - Part4.Functions Generators : 
          - 16.Functions_Basics: Python/Part4.Functions_Generators/16.Functions_Basics.md
          - 17.Scopes: Python/Part4.Functions_Generators/17.Scopes.md
          - 18.Arguments: Python/Part4.Functions_Generators/18.Arguments.md
          - 19.Function_Odds_Ends: Python/Part4.Functions_Generators/19.Function_Odds_Ends.md
          - 20.Comprehensions_Generators: Python/Part4.Functions_Generators/20.Comprehensions_Generators.md
          - 21.Benchmarking: Python/Part4.Functions_Generators/21.Benchmarking.md

      - Part5.Modules Packages : 
          - 22.Modules_Big_Picture: Python/Part5.Modules_Packages/22.Modules_Big_Picture.md
          - 23.Modules_coding_Basics: Python/Part5.Modules_Packages/23.Modules_coding_Basics.md
          - 24.Module_Packages: Python/Part5.Modules_Packages/24.Module_Packages.md
          - 25.Module_Odds_Ends: Python\Part5.Modules_Packages\25.Module_Odds_Ends.md


      - Part6.Class Oops : 
          - 26.Oops_the_Big_picture: Python/Part6.Classes_Oops/26.Oop.The_Big_Picture.md
          - 27.Class_Coding_Basics: Python/Part6.Classes_Oops/27.Class_Coding_Basics.md
          - 28.Realistic_Example: Python/Part6.Classes_Oops/28.Realistic_Example.md
          - 29.Class_Coding_Details: Python/Part6.Classes_Oops/29.Class_Coding_Details.md
          - 30.Operater_Overloading: Python/Part6.Classes_Oops/30.Operater_Overloading.md
          - 31.Designg_with_class: Python/Part6.Classes_Oops/31.Designg_with_classes.md
          - 32.Class_Odds_Ends: Python/Part6.Classes_Oops/32.Class_odds_Ends.md



#      Mk_doc\docs\Python\Part5.Modules_Packages\25.Module_Packages.md


  - Setup Guide: setup.md





markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
