site_name: Why For You
theme:
  name: material
  palette:
    - scheme: default       # Light theme
      primary: green
      accent: indigo
      toggle:
        icon: material/weather-night  # Dark mode icon
        name: Switch to dark mode
    - scheme: slate         # Dark theme
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode

# extra_css:
#       - extra.css

# extra_javascript:
#        - extra.js

#   palette:
#     scheme: default
#     primary: green
#     accent: indigo


  features:
    - navigation.tabs
    #- navigation.expand
    #- navigation.sections
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight

#
# Mk_doc\docs\Aws\3.Storage\1.S3\1.S3_General_Buckets.md

nav:

  - JavaScript_Notes:
      - Notes: JavaScript_Q&A/Notes.md
          


markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
